version: "3.7"

services:
  webapp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: onedam-server-img
    container_name: onedam-node-express
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4545:4545"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
  mongo:
    image: mongo
    container_name: onedam-mongodb
    ports:
      - "27017:27017"
